# Generated by Django 5.2.17 on 2026-09-05 01:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssistantProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("VOICE", "Voice transcript"),
                            ("IMAGE", "Image OCR text"),
                        ],
                        max_length=8,
                    ),
                ),
                ("locale", models.CharField(default="hi-IN", max_length=16)),
                ("content", models.TextField()),
                ("command_type", models.CharField(default="UNSUPPORTED", max_length=32)),
                ("payload", models.JSONField(default=dict)),
                ("preview", models.TextField(blank=True)),
                ("warnings", models.JSONField(default=list)),
                ("blocking_questions", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Needs clarification"),
                            ("READY", "Ready to confirm"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("expires_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_result_type", models.CharField(blank=True, max_length=64)),
                ("confirmed_result_id", models.UUIDField(blank=True, null=True)),
                ("confirmation_idempotency_key", models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
