# Generated by Django 5.2.17 on 2026-09-05 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assistant", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantproposal",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assistant_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assistantproposal",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assistant_proposals",
                to="tenancy.business",
            ),
        ),
        migrations.AddField(
            model_name="assistantproposal",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assistant_proposals",
                to="tenancy.location",
            ),
        ),
        migrations.AddIndex(
            model_name="assistantproposal",
            index=models.Index(
                fields=["business", "actor", "status", "created_at"],
                name="assistant_a_busines_5918e9_idx",
            ),
        ),
    ]
