# Generated by Django 5.2.17 on 2026-09-05 01:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantproposal",
            name="data_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="ProposalRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("data_fingerprint", models.CharField(max_length=64)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="assistant.assistantproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("proposal", "version"), name="uniq_proposal_revision"
                    )
                ],
            },
        ),
    ]
