# Generated by Django 5.2.17 on 2026-09-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0005_assistantproposal_preview_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantproposal",
            name="attachments",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="assistantproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Needs clarification"),
                    ("READY", "Ready to confirm"),
                    ("PROCESSING", "Reading attachment"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
