# Generated by Django 5.2.17 on 2026-09-05 01:22

import uuid
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("SUPPLIER", "Supplier"),
                            ("BOTH", "Customer and supplier"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone_e164", models.CharField(blank=True, max_length=20)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("state_code", models.CharField(blank=True, max_length=2)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("sku", models.CharField(blank=True, max_length=64)),
                (
                    "base_unit",
                    models.CharField(
                        choices=[
                            ("PIECE", "Piece"),
                            ("KILOGRAM", "Kilogram"),
                            ("LITRE", "Litre"),
                            ("METRE", "Metre"),
                            ("SERVICE", "Service"),
                        ],
                        default="PIECE",
                        max_length=12,
                    ),
                ),
                ("track_inventory", models.BooleanField(default=True)),
                ("hsn_sac", models.CharField(blank=True, max_length=12)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductPack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.000001"))],
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
