# Generated by Django 5.2.17 on 2026-09-05 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parties",
                to="tenancy.business",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="tenancy.business",
            ),
        ),
        migrations.AddField(
            model_name="productpack",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packs",
                to="catalog.product",
            ),
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(fields=["business", "name"], name="catalog_par_busines_1d3c33_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["business", "name"], name="catalog_pro_busines_672077_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["business", "sku"], name="catalog_pro_busines_feab39_idx"),
        ),
        migrations.AddConstraint(
            model_name="productpack",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="uniq_product_pack_name"
            ),
        ),
    ]
