# Generated by Django 5.2.17 on 2026-09-05 01:22

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("RECEIPT", "Customer receipt"), ("PAYMENT", "Supplier payment")],
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI"),
                            ("CARD", "Card"),
                            ("BANK", "Bank transfer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="POSTED",
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(default="API", max_length=24)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("reversal_reason", models.CharField(blank=True, max_length=240)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="tenancy.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="tenancy.location",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="catalog.party",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="POSTED",
                        max_length=10,
                    ),
                ),
                ("number", models.CharField(max_length=48)),
                ("financial_year", models.CharField(max_length=7)),
                ("sequence_number", models.PositiveBigIntegerField()),
                ("document_date", models.DateField()),
                ("posted_at", models.DateTimeField()),
                ("source", models.CharField(default="API", max_length=24)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("reversal_reason", models.CharField(blank=True, max_length=240)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("supplier_bill_number", models.CharField(blank=True, max_length=64)),
                ("tax_inclusive", models.BooleanField(default=False)),
                ("seller_name", models.CharField(blank=True, max_length=180)),
                ("seller_gstin", models.CharField(blank=True, max_length=15)),
                ("seller_state_code", models.CharField(blank=True, max_length=2)),
                ("buyer_name", models.CharField(blank=True, max_length=200)),
                ("buyer_gstin", models.CharField(blank=True, max_length=15)),
                ("buyer_state_code", models.CharField(blank=True, max_length=2)),
                ("place_of_supply", models.CharField(blank=True, max_length=2)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "taxable_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "paid_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "due_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.business"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.location"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="catalog.party",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=180)),
                ("hsn_sac", models.CharField(blank=True, max_length=12)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                ("conversion_factor", models.DecimalField(decimal_places=6, max_digits=18)),
                ("base_quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("taxable_value", models.DecimalField(decimal_places=2, max_digits=18)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_lines",
                        to="catalog.productpack",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_lines",
                        to="catalog.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="operations.purchase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="POSTED",
                        max_length=10,
                    ),
                ),
                ("number", models.CharField(max_length=48)),
                ("financial_year", models.CharField(max_length=7)),
                ("sequence_number", models.PositiveBigIntegerField()),
                ("document_date", models.DateField()),
                ("posted_at", models.DateTimeField()),
                ("source", models.CharField(default="API", max_length=24)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("reversal_reason", models.CharField(blank=True, max_length=240)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "price_mode",
                    models.CharField(
                        choices=[("RETAIL", "Retail"), ("WHOLESALE", "Wholesale")],
                        default="RETAIL",
                        max_length=10,
                    ),
                ),
                ("tax_inclusive", models.BooleanField(default=False)),
                ("seller_name", models.CharField(blank=True, max_length=200)),
                ("seller_gstin", models.CharField(blank=True, max_length=15)),
                ("seller_address", models.TextField(blank=True)),
                ("seller_state_code", models.CharField(blank=True, max_length=2)),
                ("buyer_name", models.CharField(blank=True, max_length=180)),
                ("buyer_gstin", models.CharField(blank=True, max_length=15)),
                ("buyer_state_code", models.CharField(blank=True, max_length=2)),
                ("place_of_supply", models.CharField(blank=True, max_length=2)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "taxable_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "paid_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "due_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("negative_stock_acknowledged", models.BooleanField(default=False)),
                ("negative_stock_reason", models.CharField(blank=True, max_length=240)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.business"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="catalog.party",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.location"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="operations.payment",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_allocations",
                        to="operations.purchase",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_allocations",
                        to="operations.sale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=180)),
                ("hsn_sac", models.CharField(blank=True, max_length=12)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                ("conversion_factor", models.DecimalField(decimal_places=6, max_digits=18)),
                ("base_quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("taxable_value", models.DecimalField(decimal_places=2, max_digits=18)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_lines",
                        to="catalog.productpack",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_lines",
                        to="catalog.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="operations.sale",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="tenancy.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="tenancy.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("OPENING", "Opening stock"),
                            ("SALE", "Sale"),
                            ("SALE_REVERSAL", "Sale reversal"),
                            ("PURCHASE", "Purchase"),
                            ("PURCHASE_REVERSAL", "Purchase reversal"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("TRANSFER_OUT", "Transfer out"),
                            ("TRANSFER_IN", "Transfer in"),
                            ("TRANSFER_REVERSAL", "Transfer reversal"),
                        ],
                        max_length=24,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                ("source_type", models.CharField(max_length=32)),
                ("source_id", models.UUIDField()),
                ("note", models.CharField(blank=True, max_length=240)),
                ("occurred_at", models.DateTimeField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="tenancy.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="tenancy.location",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.productpack",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="POSTED",
                        max_length=10,
                    ),
                ),
                ("number", models.CharField(max_length=48)),
                ("financial_year", models.CharField(max_length=7)),
                ("sequence_number", models.PositiveBigIntegerField()),
                ("document_date", models.DateField()),
                ("posted_at", models.DateTimeField()),
                ("source", models.CharField(default="API", max_length=24)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("reversal_reason", models.CharField(blank=True, max_length=240)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("negative_stock_acknowledged", models.BooleanField(default=False)),
                ("negative_stock_reason", models.CharField(blank=True, max_length=240)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.business"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="tenancy.location",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.location"
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="tenancy.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTransferLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                ("conversion_factor", models.DecimalField(decimal_places=6, max_digits=18)),
                ("base_quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_lines",
                        to="catalog.productpack",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_lines",
                        to="catalog.product",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="operations.stocktransfer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope_key", models.CharField(max_length=80)),
                ("document_type", models.CharField(max_length=20)),
                ("financial_year", models.CharField(max_length=7)),
                ("next_number", models.PositiveBigIntegerField(default=1)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.business"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "scope_key", "document_type", "financial_year"),
                        name="uniq_document_sequence",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="POSTED",
                        max_length=10,
                    ),
                ),
                ("number", models.CharField(max_length=48)),
                ("financial_year", models.CharField(max_length=7)),
                ("sequence_number", models.PositiveBigIntegerField()),
                ("document_date", models.DateField()),
                ("posted_at", models.DateTimeField()),
                ("source", models.CharField(default="API", max_length=24)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("reversal_reason", models.CharField(blank=True, max_length=240)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("category", models.CharField(max_length=80)),
                ("payee", models.CharField(blank=True, max_length=180)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI"),
                            ("CARD", "Card"),
                            ("BANK", "Bank transfer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.business"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.location"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "number"), name="uniq_expense_number"
                    ),
                    models.UniqueConstraint(
                        fields=("business", "created_by", "idempotency_key"),
                        name="uniq_expense_idempotency",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartyLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.CharField(
                        choices=[
                            ("RECEIVABLE", "Customer receivable"),
                            ("PAYABLE", "Supplier payable"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("source_type", models.CharField(max_length=32)),
                ("source_id", models.UUIDField()),
                ("note", models.CharField(blank=True, max_length=240)),
                ("occurred_at", models.DateTimeField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="party_ledger_entries",
                        to="tenancy.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="party_ledger_entries",
                        to="tenancy.location",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="catalog.party",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business", "party", "account", "occurred_at"],
                        name="operations__busines_d2344a_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("business", "created_by", "idempotency_key"),
                name="uniq_payment_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                fields=("business", "number"), name="uniq_purchase_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                fields=("business", "created_by", "idempotency_key"),
                name="uniq_purchase_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                fields=("business", "number"), name="uniq_sale_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                fields=("business", "created_by", "idempotency_key"), name="uniq_sale_idempotency"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("purchase__isnull", True), ("sale__isnull", False)),
                    models.Q(("purchase__isnull", False), ("sale__isnull", True)),
                    _connector="OR",
                ),
                name="allocation_exactly_one_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.UniqueConstraint(
                fields=("business", "location", "product"), name="uniq_stock_balance"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["business", "location", "product", "occurred_at"],
                name="operations__busines_aa553c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.UniqueConstraint(
                fields=("business", "number"), name="uniq_transfer_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.UniqueConstraint(
                fields=("business", "created_by", "idempotency_key"),
                name="uniq_transfer_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_location", models.F("to_location")), _negated=True),
                name="transfer_locations_differ",
            ),
        ),
    ]
