# Generated by Django 5.2.17 on 2026-09-13 01:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.operations.models
from apps.tenancy import rls


def _app_role() -> str:
    return getattr(settings, "DUKAAN_APP_DB_ROLE", rls.DEFAULT_APP_ROLE)


def _quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _apply_table_rls(schema_editor, table: str) -> None:
    role = _quote_ident(_app_role())
    quoted = _quote_ident(table)
    schema_editor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
    using, check = rls.direct_policy()
    schema_editor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
    schema_editor.execute(
        f"CREATE POLICY tenant_isolation ON {quoted} "
        f"FOR ALL TO PUBLIC USING ({using}) WITH CHECK ({check})"
    )
    schema_editor.execute(
        "DO $$ BEGIN "
        f"IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{_app_role()}') THEN "
        f"EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON {quoted} TO {role}'; "
        "END IF; END $$"
    )


def _remove_table_rls(schema_editor, table: str) -> None:
    quoted = _quote_ident(table)
    schema_editor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
    schema_editor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


def apply_phase3_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in ("operations_reminder", "operations_exportjob", "operations_attachment"):
        _apply_table_rls(schema_editor, table)


def remove_phase3_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in ("operations_reminder", "operations_exportjob", "operations_attachment"):
        _remove_table_rls(schema_editor, table)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_money_minor"),
        ("operations", "0002_money_minor"),
        ("tenancy", "0004_notificationpreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(default="sale-invoice", max_length=32)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=apps.operations.models._phase3_upload_to
                    ),
                ),
                ("mime_type", models.CharField(default="application/pdf", max_length=80)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("READY", "Ready"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="tenancy.business",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="operations.sale",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business", "status", "created_at"],
                        name="operations__busines_f888f0_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "kind", "sale"), name="uniq_attachment_sale_kind"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report", models.CharField(max_length=32)),
                (
                    "format",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("PDF", "PDF")], default="CSV", max_length=8
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=apps.operations.models._phase3_upload_to
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_jobs",
                        to="tenancy.business",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business", "status", "created_at"],
                        name="operations__busines_d28790_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("SHARE", "Manual share"),
                        ],
                        default="SHARE",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("amount_minor", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=160)),
                ("last_error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="tenancy.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="tenancy.location",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="catalog.party",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business", "status", "created_at"],
                        name="operations__busines_8d6222_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(apply_phase3_rls, remove_phase3_rls),
    ]
