# Generated by Django 5.2.17 on 2026-09-12 17:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.tenancy import rls


def _app_role() -> str:
    return getattr(settings, "DUKAAN_APP_DB_ROLE", rls.DEFAULT_APP_ROLE)


def _quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def apply_invitation_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    role = _quote_ident(_app_role())
    quoted = _quote_ident("tenancy_invitation")
    schema_editor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
    using, check = rls.direct_policy()
    schema_editor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
    schema_editor.execute(
        f"CREATE POLICY tenant_isolation ON {quoted} "
        f"FOR ALL TO PUBLIC USING ({using}) WITH CHECK ({check})"
    )
    schema_editor.execute(
        "DO $$ BEGIN "
        f"IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{_app_role()}') THEN "
        f"EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON {quoted} TO {role}'; "
        "END IF; END $$"
    )


def remove_invitation_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = _quote_ident("tenancy_invitation")
    schema_editor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
    schema_editor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_row_level_security"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="default_price_mode",
            field=models.CharField(default="RETAIL", max_length=10),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_e164", models.CharField(db_index=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("CASHIER", "Cashier"),
                        ],
                        max_length=10,
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitations",
                        to="tenancy.business",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True, related_name="invitations", to="tenancy.location"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business", "status", "created_at"],
                        name="tenancy_inv_busines_f0d89a_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(apply_invitation_rls, remove_invitation_rls),
    ]
