# Generated by Django 5.2.17 on 2026-09-13 01:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.tenancy import rls


def _app_role() -> str:
    return getattr(settings, "DUKAAN_APP_DB_ROLE", rls.DEFAULT_APP_ROLE)


def _quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def apply_notification_pref_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    role = _quote_ident(_app_role())
    quoted = _quote_ident("tenancy_notificationpreference")
    schema_editor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
    using, check = rls.direct_policy()
    schema_editor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
    schema_editor.execute(
        f"CREATE POLICY tenant_isolation ON {quoted} "
        f"FOR ALL TO PUBLIC USING ({using}) WITH CHECK ({check})"
    )
    schema_editor.execute(
        "DO $$ BEGIN "
        f"IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{_app_role()}') THEN "
        f"EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON {quoted} TO {role}'; "
        "END IF; END $$"
    )


def remove_notification_pref_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = _quote_ident("tenancy_notificationpreference")
    schema_editor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
    schema_editor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0003_business_default_price_mode_invitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=True)),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                ("daily_summary", models.BooleanField(default=True)),
                ("low_stock_alerts", models.BooleanField(default=True)),
                ("due_reminders", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_preferences",
                        to="tenancy.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "user"), name="uniq_notification_pref"
                    )
                ],
            },
        ),
        migrations.RunPython(apply_notification_pref_rls, remove_notification_pref_rls),
    ]
